# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Gentoo Theme"
license = "MIT"
licenselink = "https://github.com/grem11n/hugo-gentoo-theme/blob/master/LICENSE.md"
description = "This is a fork of https://github.com/dsk52/hugo-gentoo-theme, which is archived now"
homepage = "https://github.com/grem11n/hugo-gentoo-theme"
tags = ["blog", "responsive"]
features = ["blog", "themes", "responsive", "Google Analytics"]
min_version = 0.19

authors = [
  {name = "Daisuke Konishi", homepage = "https://blog.daisukekonishi.com"},
  {name = "Yurii Rochniak", homepage = "https://grem1.in"}
]

# If porting an existing theme
[original]
  name = "Gentoo"
  homepage = "https://github.com/d-kusk/hugo-gentoo-theme/"
  repo = "https://github.com/d-kusk/hugo-gentoo-theme/"

[params]
  dateformat = "2020-01-02" # Optional
