baseURL = "https://example.com"
title = "Gentoo"
languageCode = "en-us"
theme = "gentoo"
googleAnalytics = ""
copyright = "&copy; Copyright Year, Your Name"
canonifyurls = true
paginate = 6

[params]
  description = "This website is using Gentoo theme"

  # mainSections configures, pages from which sections will be listed on the main page
  mainSections = ["post", "posts"]

[taxonomies]
  # categories are rendered in top menu
  category = "categories"
  tag = "tags"
  series = "series"


# You can also configure static pages on your website.
# to make it work, you need to have corresponding subdirectory under content/ dir with index.md
# In this particular case it would be:
# content/about/index.md
#
[[menu.global]]
    name = "About"
    url = "/about/"

# You can configure links to your social media
[params.social]
    twitter       = ""
    github        = ""
    telegram      = ""
    email         = ""
    linkedin      = ""
    stackoverflow = ""
